### ISSUE TITLE
10月8日至10月19日 Circle STARKs 学习小组

### ISSUE THREAD

**Issue by qijinzing** [Antalpha-Labs/zkp-academy#61]
一周线上一周线下

**Comment by HaroldGin931** [comment]
这个可以关掉了吧，用不用吧 youtube 视频的链接更新到这里来？

**Comment by qijinzing** [comment]
视频链接在这里
https://www.youtube.com/playlist?list=PLbQFt1T_44DyihAOawprEABRPWgYeXB5u
